# Generated by Django 3.1.5 on 2021-04-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20210317_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('consumer_id', models.IntegerField(unique=True)),
                ('sub_station', models.CharField(max_length=50)),
                ('area_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(0, 'Electricity Outage'), (1, 'Employee Complaint'), (2, 'Suggestions')])),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.consumer')),
            ],
        ),
    ]
