# Generated by Django 3.1.5 on 2021-04-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_consumer_employee_registercomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercomplaint',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='registercomplaint',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
