# Generated by Django 3.1.5 on 2021-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_auto_20210407_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registercomplaint',
            name='consumer_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
