# Generated by Django 3.1.5 on 2021-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_auto_20210407_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomplaint',
            name='category',
            field=models.CharField(choices=[('Electricity Outage', 'Electricity Outage'), ('Employee Complaint', 'Employee Complaint'), ('Suggestions', 'Suggestions')], max_length=50),
        ),
    ]
