# Generated by Django 3.1.5 on 2021-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_auto_20210407_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercomplaint',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10),
        ),
    ]
