# Generated by Django 3.1.5 on 2021-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_registercomplaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercomplaint',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
